---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]

suites:
- name: webgoat
  run_list:
  - recipe[java]
  - recipe[tomcat]
  - recipe[tomcat::users]
  - recipe[webgoat]
  attributes:
    tomcat:
      base_version: 7
