---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: debian-7.6
  run_list:
  - recipe[apt]

suites:
- name: webgoat
  run_list:
  - recipe[webgoat]
  attributes:
    webgoat:
      path: /opt/wg
      port: 8081
